# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'NativeStarterKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  # Pods for NativeStarterKit

  target 'NativeStarterKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeStarterKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end



  # Pods for NativeStarterKit-tvOS

  target 'NativeStarterKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
