# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Blured' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   # use_frameworks!
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

  # Pods for ReactPushNotifications - Add these lines

    pod 'GoogleAppMeasurement', '~> 5.2.0'




  pod 'Firebase', '~> 5.0.1'
  pod 'Firebase/Core', '~> 5.0.1'
  pod 'Firebase/Messaging', '~> 5.0.1'


  # Pods for NativeStarterKit

target 'Blured-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BluredTests' do
    inherit! :search_paths
    # Pods for testing
  end

end